import { Aluno } from "@/lib/types/aluno";

export const ALUNOS_MOCK: Aluno[] = [
  {
    id: "aluno-001",
    nome: "Miguel Santos",
    idade: 8,
    iniciais: "MS",
    corAvatar: "#F5C518",
    diagnostico: "Síndrome de Down",
    turno: "Manhã",
    responsavelAPAE: {
      nome: "Profa. Ana Lima",
      area: "Escola",
      foto: null,
    },
    familia: {
      responsavel: "Maria Santos",
      parentesco: "Mãe",
      telefone: "(35) 99812-3456",
      engajamento: 92,
    },
    areas: ["Escola", "Saúde", "Terapia Ocupacional", "Fonoaudiologia"],
    cronograma: [
      { diaSemana: "Segunda", horario: "08:00", area: "Escola" },
      { diaSemana: "Quarta", horario: "08:00", area: "Terapia Ocupacional" },
      { diaSemana: "Sexta", horario: "09:00", area: "Fonoaudiologia" },
    ],
    metasAno: [
      "Desenvolver comunicação verbal básica",
      "Autonomia para se alimentar sozinho",
      "Socialização com colegas",
    ],
    ultimoRegistro: "2024-07-22",
    diasSemRegistro: 1,
    evolucaoGeral: 78,
    evolucaoPorArea: [
      { area: "Escola", valor: 72 },
      { area: "Saúde", valor: 88 },
      { area: "Terapia Ocupacional", valor: 65 },
      { area: "Fonoaudiologia", valor: 70 },
    ],
    evolucaoMensal: [
      { mes: "Mar", valor: 45 },
      { mes: "Abr", valor: 52 },
      { mes: "Mai", valor: 61 },
      { mes: "Jun", valor: 68 },
      { mes: "Jul", valor: 78 },
    ],
    humorMedio: 4.2,
  },
  {
    id: "aluno-002",
    nome: "Sofia Oliveira",
    idade: 6,
    iniciais: "SO",
    corAvatar: "#A78BFA",
    diagnostico: "Transtorno do Espectro Autista",
    turno: "Tarde",
    responsavelAPAE: {
      nome: "Profa. Beatriz Campos",
      area: "Escola",
      foto: null,
    },
    familia: {
      responsavel: "Juliana Oliveira",
      parentesco: "Mãe",
      telefone: "(35) 99823-4567",
      engajamento: 85,
    },
    areas: ["Escola", "Terapia Ocupacional", "Fonoaudiologia"],
    cronograma: [
      { diaSemana: "Terça", horario: "14:00", area: "Escola" },
      { diaSemana: "Quinta", horario: "14:00", area: "Fonoaudiologia" },
      { diaSemana: "Sexta", horario: "15:00", area: "Terapia Ocupacional" },
    ],
    metasAno: [
      "Ampliar vocabulário funcional",
      "Tolerar ambientes com mais estimulação",
      "Interação social com um colega",
    ],
    ultimoRegistro: "2024-07-21",
    diasSemRegistro: 2,
    evolucaoGeral: 65,
    evolucaoPorArea: [
      { area: "Escola", valor: 58 },
      { area: "Terapia Ocupacional", valor: 70 },
      { area: "Fonoaudiologia", valor: 62 },
    ],
    evolucaoMensal: [
      { mes: "Mar", valor: 35 },
      { mes: "Abr", valor: 42 },
      { mes: "Mai", valor: 50 },
      { mes: "Jun", valor: 58 },
      { mes: "Jul", valor: 65 },
    ],
    humorMedio: 3.4,
  },
  {
    id: "aluno-003",
    nome: "Pedro Alves",
    idade: 10,
    iniciais: "PA",
    corAvatar: "#3B82F6",
    diagnostico: "Paralisia Cerebral",
    turno: "Manhã",
    responsavelAPAE: {
      nome: "Fisio. Carlos Mendes",
      area: "Fisioterapia",
      foto: null,
    },
    familia: {
      responsavel: "Roberto Alves",
      parentesco: "Pai",
      telefone: "(35) 99834-5678",
      engajamento: 54,
    },
    areas: ["Escola", "Fisioterapia", "Terapia Ocupacional", "Saúde"],
    cronograma: [
      { diaSemana: "Segunda", horario: "09:00", area: "Fisioterapia" },
      { diaSemana: "Quarta", horario: "09:00", area: "Escola" },
      { diaSemana: "Sexta", horario: "10:00", area: "Terapia Ocupacional" },
    ],
    metasAno: [
      "Melhorar equilíbrio sentado",
      "Usar comunicador alternativo",
      "Participar de atividades em grupo",
    ],
    ultimoRegistro: "2024-07-15",
    diasSemRegistro: 8,
    evolucaoGeral: 48,
    evolucaoPorArea: [
      { area: "Escola", valor: 40 },
      { area: "Fisioterapia", valor: 62 },
      { area: "Terapia Ocupacional", valor: 45 },
      { area: "Saúde", valor: 55 },
    ],
    evolucaoMensal: [
      { mes: "Mar", valor: 28 },
      { mes: "Abr", valor: 33 },
      { mes: "Mai", valor: 38 },
      { mes: "Jun", valor: 44 },
      { mes: "Jul", valor: 48 },
    ],
    humorMedio: 3.8,
  },
  {
    id: "aluno-004",
    nome: "Laura Ferreira",
    idade: 9,
    iniciais: "LF",
    corAvatar: "#F97316",
    diagnostico: "Deficiência Intelectual",
    turno: "Tarde",
    responsavelAPAE: {
      nome: "Profa. Ana Lima",
      area: "Escola",
      foto: null,
    },
    familia: {
      responsavel: "Cláudia Ferreira",
      parentesco: "Mãe",
      telefone: "(35) 99845-6789",
      engajamento: 71,
    },
    areas: ["Escola", "Fonoaudiologia", "Saúde"],
    cronograma: [
      { diaSemana: "Terça", horario: "13:00", area: "Escola" },
      { diaSemana: "Quinta", horario: "13:00", area: "Fonoaudiologia" },
    ],
    metasAno: [
      "Escrever o próprio nome",
      "Contar até 10 com compreensão",
      "Seguir instruções de 2 etapas",
    ],
    ultimoRegistro: "2024-07-20",
    diasSemRegistro: 3,
    evolucaoGeral: 61,
    evolucaoPorArea: [
      { area: "Escola", valor: 55 },
      { area: "Fonoaudiologia", valor: 68 },
      { area: "Saúde", valor: 72 },
    ],
    evolucaoMensal: [
      { mes: "Mar", valor: 38 },
      { mes: "Abr", valor: 45 },
      { mes: "Mai", valor: 52 },
      { mes: "Jun", valor: 57 },
      { mes: "Jul", valor: 61 },
    ],
    humorMedio: 4.0,
  },
  {
    id: "aluno-005",
    nome: "Gabriel Costa",
    idade: 7,
    iniciais: "GC",
    corAvatar: "#10B981",
    diagnostico: "Síndrome de Williams",
    turno: "Manhã",
    responsavelAPAE: {
      nome: "Profa. Beatriz Campos",
      area: "Escola",
      foto: null,
    },
    familia: {
      responsavel: "Fernanda Costa",
      parentesco: "Mãe",
      telefone: "(35) 99856-7890",
      engajamento: 88,
    },
    areas: ["Escola", "Terapia Ocupacional", "Fonoaudiologia", "Saúde"],
    cronograma: [
      { diaSemana: "Segunda", horario: "08:30", area: "Escola" },
      { diaSemana: "Terça", horario: "09:00", area: "Fonoaudiologia" },
      { diaSemana: "Quinta", horario: "09:00", area: "Terapia Ocupacional" },
    ],
    metasAno: [
      "Desenvolver concentração em tarefas",
      "Reduzir hipersensibilidade sonora",
      "Ampliar autonomia nas refeições",
    ],
    ultimoRegistro: "2024-07-22",
    diasSemRegistro: 1,
    evolucaoGeral: 74,
    evolucaoPorArea: [
      { area: "Escola", valor: 70 },
      { area: "Terapia Ocupacional", valor: 78 },
      { area: "Fonoaudiologia", valor: 72 },
      { area: "Saúde", valor: 80 },
    ],
    evolucaoMensal: [
      { mes: "Mar", valor: 48 },
      { mes: "Abr", valor: 55 },
      { mes: "Mai", valor: 62 },
      { mes: "Jun", valor: 69 },
      { mes: "Jul", valor: 74 },
    ],
    humorMedio: 4.5,
  },
  {
    id: "aluno-006",
    nome: "Isabela Nunes",
    idade: 11,
    iniciais: "IN",
    corAvatar: "#EC4899",
    diagnostico: "Deficiência Visual",
    turno: "Tarde",
    responsavelAPAE: {
      nome: "Profa. Ana Lima",
      area: "Escola",
      foto: null,
    },
    familia: {
      responsavel: "Marcos Nunes",
      parentesco: "Pai",
      telefone: "(35) 99867-8901",
      engajamento: 40,
    },
    areas: ["Escola", "Terapia Ocupacional", "Saúde"],
    cronograma: [
      { diaSemana: "Terça", horario: "14:30", area: "Escola" },
      { diaSemana: "Quinta", horario: "15:00", area: "Terapia Ocupacional" },
    ],
    metasAno: [
      "Aprender Braille básico",
      "Orientação e mobilidade no espaço escolar",
      "Uso de tecnologia assistiva",
    ],
    ultimoRegistro: "2024-07-10",
    diasSemRegistro: 13,
    evolucaoGeral: 56,
    evolucaoPorArea: [
      { area: "Escola", valor: 50 },
      { area: "Terapia Ocupacional", valor: 64 },
      { area: "Saúde", valor: 68 },
    ],
    evolucaoMensal: [
      { mes: "Mar", valor: 30 },
      { mes: "Abr", valor: 38 },
      { mes: "Mai", valor: 44 },
      { mes: "Jun", valor: 50 },
      { mes: "Jul", valor: 56 },
    ],
    humorMedio: 3.6,
  },
];
