import { Professor } from "@/lib/types/usuario";

export const PROFESSORES_MOCK: Professor[] = [
  {
    id: "prof-001",
    nome: "Ana Lima",
    iniciais: "AL",
    corAvatar: "#F5C518",
    area: "Escola",
    totalAlunos: 12,
    registrosSemana: 18,
    engajamentoFamilias: 82,
    ultimoAcesso: "2024-07-22",
  },
  {
    id: "prof-002",
    nome: "Beatriz Campos",
    iniciais: "BC",
    corAvatar: "#A78BFA",
    area: "Escola",
    totalAlunos: 10,
    registrosSemana: 15,
    engajamentoFamilias: 74,
    ultimoAcesso: "2024-07-22",
  },
  {
    id: "prof-003",
    nome: "Carlos Mendes",
    iniciais: "CM",
    corAvatar: "#3B82F6",
    area: "Fisioterapia",
    totalAlunos: 8,
    registrosSemana: 12,
    engajamentoFamilias: 61,
    ultimoAcesso: "2024-07-21",
  },
  {
    id: "prof-004",
    nome: "Carla Souza",
    iniciais: "CS",
    corAvatar: "#10B981",
    area: "Terapia Ocupacional",
    totalAlunos: 14,
    registrosSemana: 20,
    engajamentoFamilias: 78,
    ultimoAcesso: "2024-07-22",
  },
  {
    id: "prof-005",
    nome: "Renata Vieira",
    iniciais: "RV",
    corAvatar: "#F97316",
    area: "Fonoaudiologia",
    totalAlunos: 11,
    registrosSemana: 16,
    engajamentoFamilias: 69,
    ultimoAcesso: "2024-07-20",
  },
  {
    id: "prof-006",
    nome: "Fernando Lima",
    iniciais: "FL",
    corAvatar: "#EC4899",
    area: "Saúde",
    totalAlunos: 9,
    registrosSemana: 8,
    engajamentoFamilias: 55,
    ultimoAcesso: "2024-07-18",
  },
];
